### ISSUE TITLE
Installer not removing/closing old version

### ISSUE THREAD

**Issue by traynier** [lanayotech/vagrant-manager-windows#1]
First off, awesome work!  I love it. :)

A few oddites in the "Check Update" and installing 1.0.0.2 over 1.0.0.1.

1. Have 1.0.0.1 installed.
2. Check updates, and download and run the 1.0.0.2 installer
3. It complains about Vagrant manager already running, and offers to close it.  However, it does not close cleanly and fails - the icon disappears from the taskbar but it is still running as a process until I kill it in Task Manager.
4. I now have both 1.0.0.1 and 1.0.0.2 listed in Windows "Uninstall a program" - ideally it should remove 1.0.0.1 as part of the 1.0.0.2 install.
5. It also seemed to lose my bookmarks

**Comment by cfoellmann** [comment]
Maybe using a different update library? https://autoupdaterdotnet.codeplex.com/ 
Or did you report the issue to https://github.com/sparkle-project/Sparkle ? If this is the right library.

**Comment by cfoellmann** [comment]
Sorry- Was not the right library.
You use https://github.com/sparkle-project/Sparkle , right? Seems very outdated. Maybe there is the problem.

**Comment by amitailanciano** [comment]
Sparkle only checks for updates and notifies users when an update is available, it will also download the executable for you, all of which works well; the problem appears to be related to the actual installer. Right now we're using [Inno Setup](http://www.jrsoftware.org/isinfo.php), but at this point we'll probably try using the built-in Visual Studio tools to package it and see if that resolves the issue.

**Comment by amitailanciano** [comment]
This should be resolved in 1.0.0.4
