### ISSUE TITLE
Make the output window default to using a monospace font and being at least 80 characters wide

### ISSUE THREAD

**Issue by ataylor32** [lanayotech/vagrant-manager-windows#10]
Command Prompt defaults to using a monospace font and being 80 characters wide. Scripts often expect this type of setup. As an example of something that would benefit from this change, here is a screen shot of Command Prompt at the end of `vagrant up` with [PuPHPet](https://puphpet.com/):

![command-prompt](https://cloud.githubusercontent.com/assets/1054222/6152128/f945ebd8-b1d7-11e4-877b-4d78c6eb56d3.png)

And here is the same thing in Vagrant Manager (I left the window alone; I didn't resize it):

![vagrant-manager](https://cloud.githubusercontent.com/assets/1054222/6152139/06fd0b58-b1d8-11e4-9c9f-8b6ad8656f80.png)

**Comment by amitailanciano** [comment]
Good suggestion, we'll update these for the next release

**Comment by mtt-shane** [comment]
I would love this as well. At the very least, it would be awesome if Vagrant Manager would remember the last window size/position. I need to increase the width of the window every time I run it.

**Comment by ataylor32** [comment]
@mtt-shane Sadly, I don't think this will be happening. See [this comment](https://github.com/lanayotech/vagrant-manager-windows/pull/22#issuecomment-166214894) from @amitailanciano

**Comment by amitailanciano** [comment]
This was included in 1.0.0.4
