### ISSUE TITLE
Publish on Chocolatey Gallery

### ISSUE THREAD

**Issue by cfoellmann** [lanayotech/vagrant-manager-windows#12]
Do you have any objections against publishing the Vagrant Manager on https://chocolatey.org/packages ?
I would be happy to maintain the package there

**Comment by cfoellmann** [comment]
Can you provide me Some kind of logo for https://chocolatey.org/packages/vagrant-manager ? Package will be up after moderation

**Comment by amitailanciano** [comment]
No objections here, that's awesome. We don't have a logo for you, maybe just use the Vagrant logo? Here is the highest resolution of the one we use on the mac version:
![appicon-512x512 2x](https://cloud.githubusercontent.com/assets/1289466/6828350/96cdab58-d2ca-11e4-9a49-a3412939d811.png)

**Comment by cfoellmann** [comment]
what do you think about setting vagrant as a dependency? It can be done with chocolatey but it is just an option

**Comment by amitailanciano** [comment]
I think that's a good idea

**Comment by cfoellmann** [comment]
package is finished at https://chocolatey.org/packages/vagrant-manager and can already be installed by specifying the version. It will be listed on the Gallery as soon as the mods have approved it.
Should make for some downloads since it will be found together with vagrant itself

**Comment by cfoellmann** [comment]
DONE

**Comment by cfoellmann** [comment]
@amitailanciano if you register an account on https://chocolatey.org I would add you as a maintainer for the choco package. THis way you would have access if I were to do something bad or disappear.
