### ISSUE TITLE
manage vagrant machines on local ubuntu box from windows?

### ISSUE THREAD

**Issue by vesper8** [lanayotech/vagrant-manager-windows#13]
Hi there,

I'm not sure where to ask this. I initially started using your software on my windows box and it worked great, but all my sites were so slow under vagrant. I got to understand this was a side-effect of not using NFS and heard there was a fix under linux and mac but not so much windows (there's something but it seems iffy).

So now I've installed my VMs under my ubuntu local box and I am wondering if there's a way to manage them using Vagrant Manager for Windows?

If there is, or if you know of another solution.. could you please share it?

Many thanks

**Comment by amitailanciano** [comment]
Unfortunately there is currently no linux version of Vagrant Manager, we'll make an announcement on the website if we ever port it
