### ISSUE TITLE
VAGRANT_DOTFILE_PATH system variable is ignored

### ISSUE THREAD

**Issue by gambolputty** [lanayotech/vagrant-manager-windows#14]
Hello,

on my Windows 8 machine, the `VAGRANT_DOTFILE_PATH` is `.vagrant-desktop`.
When I run my Vagrant box with Vagrant Manager (Context menu >> MyMachine >> Up), the system variable `VAGRANT_DOTFILE_PATH` is being ignored.

Instead, the old `.vagrant`-folder is newly created and the host runs form there.

Unfortunaly this makes using Vagrant Manager pointless to me, because I have to manage my hosts via custom DOTFILE_PATHs. Could you pleeeaase fix that?

Regards,
Gregor

**Comment by crayfishuk** [comment]
+1 please.  It's now completely unusable for our team too... :(

**Comment by amitailanciano** [comment]
I'm not sure what the issue might be with this one, vagrant manager just kicks off a process using your local environment -- I ran a test (below) after adding `VAGRANT_DOTFILE_PATH` in my system environment variables and it appeared in the process environment variables (and proceeded to run the action correctly respecting the path provided)

I'm sure you've already checked, but maybe there's a misspelling in your constant name? If you can provide any other information about your environment/configuration/tooling I might be able to help further.

![environment_variables](https://cloud.githubusercontent.com/assets/1289466/15106307/58e64542-157d-11e6-9346-51d479b19cae.png)

**Comment by amitailanciano** [comment]
no reply, closing for now
