### ISSUE TITLE
Error on Installation when not using VirtualBox

### ISSUE THREAD

**Issue by PanadeEdu** [lanayotech/vagrant-manager-windows#15]
This tool seems to suppor everz VM Provider, why is VirtualBox at installation checked and throws an Error if not existend. 

I am using VMWare, so this throws an Error for no real reason since the installation runns trough and it can Detect VMWare. 
Please remove this Error from the installation process.

**Comment by amitailanciano** [comment]
I agree, this error will be removed

**Comment by amitailanciano** [comment]
Resolved by 1.0.0.5
