### ISSUE TITLE
VMWare requires Admin Previleges on Windows

### ISSUE THREAD

**Issue by PanadeEdu** [lanayotech/vagrant-manager-windows#16]
VMWare needs Admin Previleges on Windows to run. Also VirtualBox Settings can require Admin Previleges (symlink support). 

Please add an easy way to support start on Admin Previleges, since it is required in some cases.
A Setting would be the most comfortable way of doing this.

**Comment by adamdyson** [comment]
I just discovered this myself. Uninstalling for now, until VMWare (workstation) is supported.

**Comment by amitailanciano** [comment]
Ticking the 'Run as Administrator' option on the executable should resolve this

**Comment by PanadeEdu** [comment]
it is not a bug, and can resolved as described. But for usability reasons it should be considered as a feature since you can advice windows to ask for admin previleges.
