### ISSUE TITLE
windows 10 need the administrator role

### ISSUE THREAD

**Issue by icai** [lanayotech/vagrant-manager-windows#25]
windows 10 need the administrator role(permission)

The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:
There was an error running VBoxManage. This is usually a permissions
problem or installation problem with VirtualBox itself, and not Vagrant.
Please note the error message below (if any), resolve the issue, and
try Vagrant again.
请求的操作需要提升。 (740)

**Comment by amitailanciano** [comment]
This is a permissions issue unrelated to vagrant manager
