### ISSUE TITLE
Zipped release 1.0.0.4 is 1.0.0.3

### ISSUE THREAD

**Issue by Prometee** [lanayotech/vagrant-manager-windows#27]
Hi,

It seems that release 1.0.0.4 is 1.0.0.3, because the about windows shows version 1.0.0.3
And refreshing don't stop saying "Refreshing ..." with no disk activity after 8 hours running.

**Comment by amitailanciano** [comment]
Release 1.0.0.5 should resolve this

**Comment by Prometee** [comment]
Perfect it works :)
