### ISSUE TITLE
Never finds my vagrant boxes

### ISSUE THREAD

**Issue by ssnyder** [lanayotech/vagrant-manager-windows#28]
I have installed 1.0.5, and when it starts, it starts to look for the boxes I have installed, and never finishes that task, so my list of boxes never shows up.  On and this is on Windows 7.

**Comment by syntacticvexation** [comment]
+1.  I see a "Refreshing" label that doesn't change on Windows 10.

**Comment by noahziheng** [comment]
Same problem.Windows 10 Pro.

**Comment by amitailanciano** [comment]
What version of Vagrant are you using?

**Comment by noahziheng** [comment]
@amitailanciano Vagrant 1.8.5

**Comment by syntacticvexation** [comment]
Same - Vagrant 1.8.5.  Is there a particular folder structure it is expecting?

**Comment by MarkSummers** [comment]
We're seeing this issue too.

I tried to debug VagrantManager in Visual Studio 2015 and it seems that Process.WaitForExit() is blocking on this command:

`VBoxManage showvminfo {uuid} --machinereadable`

I captured the exact command string and ran it in cmd.exe and it returned as expected.

**Comment by MarkSummers** [comment]
I think I found the cause of the issue:  The contents of the process standard out needs to be read before WaitForExit() to prevent a deadlock.

https://msdn.microsoft.com/en-us/library/system.diagnostics.process.standardoutput(v=vs.110).aspx

```
// To avoid deadlocks, always read the output stream first and then wait.
string output = p.StandardOutput.ReadToEnd();
p.WaitForExit();
```

This approach seems to have resolved the issue:

```
string outputString = p.StandardOutput.ReadToEnd();
p.WaitForExit();
outputString += p.StandardOutput.ReadToEnd();
```

**Comment by narration-sd** [comment]
Mark, I complimented you on the original thread, and suggested a pull request.

Seeing that both it and this bug thread are closed, not sure if @amitailanciano will be seeing your work notified, so tha pull request maybe even more worthwhile, esp. since this change is so small if likely potent.

Kind regards,
Clive

**Comment by MarkSummers** [comment]
PR created:

https://github.com/lanayotech/vagrant-manager-windows/pull/34/files

**Comment by narration-sd** [comment]
Good man ;)

**Comment by amitailanciano** [comment]
Release [1.0.0.6](https://github.com/lanayotech/vagrant-manager-windows/releases/tag/1.0.0.6) should resolve this issue, thanks again for your contribution @MarkSummers
