### ISSUE TITLE
Plugin's support 

### ISSUE THREAD

**Issue by MekDrop** [lanayotech/vagrant-manager-windows#30]
I think this project looks good and promising to be a must have for every developer tool, however this how development goes that doesn't looks good for me. I thought I would create a similar project for same purposes like vagrant-manager but I don't have much time to spend for doing something useful :(

But maybe we can rethink instead how this project is developed and how it works. Maybe instead of adding new futures we can add plug-ins support and everybody can add own functionality? Maybe we could create a platform like Unity has where everyone can publish own things and maybe earn money? Maybe that could make this project more alive? ;)

**Comment by amitailanciano** [comment]
#31

**Comment by amitailanciano** [comment]
I think those are interesting ideas, but ultimately beyond the scope of this project at this time.
