### ISSUE TITLE
Provide release .exe on GitHub

### ISSUE THREAD

**Issue by cfoellmann** [lanayotech/vagrant-manager-windows#36]
I was looking to update the CHocolatey package which is way behind https://chocolatey.org/packages/vagrant-manager
And realized the release changed from .exe to .zip containing the .exe file.

Can you please upload the .exe to the release packages? So I can update the chocolatey installer package

THX

**Comment by mukrop** [comment]
+1
Or is there a reason not to include the EXE file directly?

**Comment by amitailanciano** [comment]
I think when I first released it, Github didn't let me upload the EXE directly -- I'll try it for the next release if I find that's not an issue anymore (perhaps it never was? It was quite a long time ago).

**Comment by chriswayoub** [comment]
The latest release now provides an .exe instead of a .zip
