### ISSUE TITLE
Feature request: Run as Administrator

### ISSUE THREAD

**Issue by Sophie-de-Lalalie** [lanayotech/vagrant-manager-windows#38]
Hi,
i would be nice, if i could tell the app, that all vagrant commands should be executed as administrator. As long as this is not possible, i can't use your practical application under Windows 10, since symlinking inside the shared folder is allowed only for administrators (somehow).

**Comment by groovenectar** [comment]
You can go to the properties of the shortcut and under Compatibility set it to run as Administrator... I'm in the same situation with symlinking...
