### ISSUE TITLE
The menu should use real machine names

### ISSUE THREAD

**Issue by antoniodeluca** [lanayotech/vagrant-manager-windows#40]
The menu currently shows items named after the folder names of the various Vagrantfile(s). Would be better to use the name provided by the Vagrantfile like in this case:

Vagrant.configure(2) do |config|
  ...
  ...
  ...
  config.vm.provider "virtualbox" do |vb|
    vb.name = "name of the machine"
    ...
    ...
  end  
end

Thanks for your great work!

**Comment by amitailanciano** [comment]
There is an option in the preferences to include the machine name in the menu item label, I don't think we'll be changing the default folder naming convention since that's how it has worked since the beginning on OS X as well.
