### ISSUE TITLE
stdin is not a tty

### ISSUE THREAD

**Issue by Gauss23** [lanayotech/vagrant-manager-windows#45]
Hello,

I´m using vagrant-manager for a while now and it was running flawlessly. I updated Virtualbox to version **5.1.26** and Vagrant to **1.9.7** and now vagrant manager is not able to start my boxes anymore. It even does not detect the state of the vagrant boxes. It shows all boxes listed in Virtualbox with a red dot. I can use the "SSH" command from vagrant-manager, if the box is running. 

When I click on "up" it opens a window where the messages of the box are shown usually but it simply says: 

> stdin is not a tty

 and that´s it. On the top is written: 

> completed with errors

When I open a cmd prompt and start the boxes on my own with `vagrant up`  everything is ok, Tried uninstalling everything and reinstalled, even deleted the vagrant-manager settings. Still 

> stdin is not a tty

How can I debug this? Is it an issue with the new version of Virtualbox or Vagrant?

Best regards

**Comment by mcrump001** [comment]
I have the same configuration and confirm that I am seeing the same issue.

**Comment by mcrump001** [comment]
This appears to be an issue with Vagrant 1.9.7 as documented here:

[Vagrant Issue 8764](https://github.com/mitchellh/vagrant/issues/8764)

I reverted my local Vagrant install to version 1.9.6 and all is well.

**Comment by Gauss23** [comment]
Thank you for sharing this information. Will downgrade for the moment.
