### ISSUE TITLE
Not working with Vagrant 2.0.1

### ISSUE THREAD

**Issue by mtt-shane** [lanayotech/vagrant-manager-windows#47]
I was forced to update to Vagrant 2.0.1 today (Win 10 Fall Creators update necessitates Virtualbox update, which necessitates Vagrant update). Now Vagrant Manager is stuck refreshing and will not show my machines.

EDIT: Should mention that I'm running VirtualBox 5.2.0 now.

**Comment by wireblue** [comment]
Downgrading to Vagrant 2.0.0 and VirtualBox 5.1.30 fixed this issue for me.

I was previously running Vagrant 2.0.1 and VirtualBox 5.2.0 and was seeing the same issue (Vagrant Manager was constantly refreshing and not loading any of the bookmarked boxes).

**Comment by mtt-shane** [comment]
Thanks @wireblue . Did you do anything special to downgrade, or did you just uninstall/reinstall both?

**Comment by wireblue** [comment]
Nothing special. Just uninstalled/reinstalled both.

**Comment by ZStelmo** [comment]
I do the same, but lost all my vagrant boxes.

Em 15/11/2017 9:30 da tarde, "Kyle Stevenson" <notifications@github.com>
escreveu:

**Comment by mtt-shane** [comment]
Downgrading to Vagrant 2.0.0 and VirtualBox 5.1.30 worked for me as well, and I didn't lose any boxes. Thanks again @wireblue

**Comment by Broutard** [comment]
+1

**Comment by kmgalanakis** [comment]
Is there any chance that Vagrant Manager will be updated to support the latest Vagrant and VirtualBox?

**Comment by DevJackSmith** [comment]
The last update I see is more than a year old, might be that this project is abandoned. @amitailanciano @MarkSummers can you guys confirm if you are working on this project still or not anymore?

**Comment by amitailanciano** [comment]
I am still receiving notifications for these issues, but it's been quite a while since I've worked on this; I need to dig up the inno setup configuration file and get a working dev environment on my windows box again. I'd like to at least take care of this issue, merge pr #46, and release as an executable so it can be installed via Chocolatey.

**Comment by narration-sd** [comment]
@amitailanciano  This would be great, as perhaps many of us could not back  off to the initial Vagrant 2.0.0 version, as it had show-stoppers for many environments. 

I do miss your tool, and don't have anything of the toolset or Win dev background to fix it. Perhaps the clue can be easily seen, if indeed 2..00 allows it to work,, but 2.0.1 doesn't.

In any case, thanks for the use of it for many months, reliable and a pleasure.

**Comment by michaelthorne** [comment]
Also experiencing the "Refreshing..." issue:

Vagrant Manager `1.0.0.6`
Vagrant `2.0.1`
VirtualBox `5.2.6 r120293`

But I think the problem lies with the latest Windows update:

Edition: `Windows 10 Pro`
Version: `1709`
OS Build: `16229.125`

The other software was all running fine at those latest versions. After Windows update the other day, I noticed the "Refreshing..." issue.

**Comment by kastler-deltait** [comment]
+1
Any news?

**Comment by deveres** [comment]
https://github.com/deveres/vagrant-manager-windows/releases

Look here guys.

**Comment by Broutard** [comment]
@deveres Greeeeeeat ! It work, thanks !

**Comment by eleftrik** [comment]
Thank you @deveres, with version 1.0.0.7 everything works again!

**Comment by michaelthorne** [comment]
Nice one @deveres, appreciate it. 👍

**Comment by mtt-shane** [comment]
Awesome @deveres, thank you!

**Comment by dtrv** [comment]
+1

**Comment by deveres** [comment]
Thank's all

**Comment by narration-sd** [comment]
Many thanks @deveres  -- thought I had :)

**Comment by amitailanciano** [comment]
@deveres I sincerely appreciate your contributions and efforts keeping this project going.

Are you at all interested in maintaining this repository for the foreseeable future? It is unfortunate that the Windows version of Vagrant Manager has fallen behind in features (and maintenance) compared to the macOS version, but we do not currently have the time or resources to maintain or port over features from the macOS version. I would love to hear from you if you are interested in assuming that role.

Please contact me if you are interested, my email address is available on my profile page.

**Comment by MekDrop** [comment]
Just two my cents for last @amitailanciano comment: not long time ago I saw another [vagrant manager](https://github.com/absalomedia/vagrant-manager). But different is that it is based on Electron so same code could run on both on Windows, MacOS and some Linux distributions. I think it would be easier to use same codebase for different OS and find some contributors than develop 3 different versions for basically same thing. But I'm not sure... maybe there are things that I don't know... So in any case I wish that some good solution would be found here.

**Comment by deveres** [comment]
Hi. I am not good in c#  but i will try to keep working current
functionality of vagrant manager. I use this product. I  think new
features,i wil not be able to extend. Thank's

**Comment by amitailanciano** [comment]
thank you @deveres 

@MekDrop absolutely agree with you, we hope to do a rebuild in Electron at some point in the future to reduce the cross platform maintenance overhead, thank you for your thoughts!

**Comment by chriswayoub** [comment]
PR #48 has been merged and this is working as of 1.0.2.2
