### ISSUE TITLE
Stuck on refresh

### ISSUE THREAD

**Issue by mathewrapid** [lanayotech/vagrant-manager-windows#49]
Tested with vagrant 1.9.6 and 1.9.8. Vagrant Manager 1.0.0.6 run with admin privileges.

Vagrant manager is stuck on refresh. It spawns four ruby and vagrant processes. If the processes are then forcefully stopped, then Vagrant Manager will list all my vm's, but their state is not shown. Some machines can be started but not halt command is listed etc.

**Comment by juliocoliveira** [comment]
same

**Comment by deveres** [comment]
https://github.com/deveres/vagrant-manager-windows/releases

**Comment by juliocoliveira** [comment]
I downloaded yesterday from the website.
And your version is working just fine, Thanks!

**Comment by mathewrapid** [comment]
@deveres didn't work. Now I upgraded to Vagrant 2.0.3 and installed your 1.0.0.7. Doesn't even find any machines.

**Comment by mathewrapid** [comment]
@narration-sd then it must be my computer that is acting up. This started when I updated to Vagrant 2.x and the manager stopped working. Reverted back to Vagrant 1.9.6 and hoped for the best. Under this switcharoo, something went awry. Now no version of the manager shows any of my virtual machines.

**Comment by artursmirnov** [comment]
Does not work for me either. First tried 
- Vagrant 2.0.2
- Vagrant Manager 1.0.0.6

Then installed a chocolatey package:
- Vagrant 2.0.4
- Vagrant Manager 1.0.0.3

Still the same, always refreshing.

Although, worth mentioning, macOS version seems to have the same issue https://github.com/lanayotech/vagrant-manager/issues/167

**Comment by mbrodala** [comment]
Works fine with Vagrant 2.0.1 and Vagrant Manager 1.0.0.7 from deveres. After updating to Vagrant 2.1.1 it still seems to work fine.

**Comment by deveres** [comment]
New update for vagrant 2.2.3 and virtualbox 6.0.2

https://github.com/deveres/vagrant-manager-windows/releases

**Comment by mbrodala** [comment]
@deveres Thanks, looks good.

**Comment by chriswayoub** [comment]
PR #48 has been merged and this is working as of 1.0.2.2
