### ISSUE TITLE
Not working with vagrant 2.1.2 on Windows 10

### ISSUE THREAD

**Issue by poon64** [lanayotech/vagrant-manager-windows#51]
I have just installed the Vagrant manager 1.0.0.6 on windows 10. 
After I installed it I made all of my vagrant machines go up, but none of them were detected. 
So I added them manually with the Manage Bookmarks, but still none of them were coming up. 
I even restarted the whole machine, with the same result.

**Comment by poon64** [comment]
I have just tested the same version at work on my Windows 7 machine, it's not working there either.

**Comment by winnux** [comment]
maybe miss some virtualbox settings 
VirtualBoxMachineInfo.cs 
`
                if (value.Length>0&&value.Substring(0, 1) == "\"") {
                    value = value.Substring(1, value.Length - 2);
                }
`

**Comment by deveres** [comment]
https://github.com/lanayotech/vagrant-manager-windows/issues/47#issuecomment-363756681

**Comment by nunoguerreiro** [comment]
> I have just installed the Vagrant manager 1.0.0.6 on windows 10.
> After I installed it I made all of my vagrant machines go up, but none of them were detected.
> So I added them manually with the Manage Bookmarks, but still none of them were coming up.
> I even restarted the whole machine, with the same result.

The same with me. Vagrant 2.2.6; Windows 10 Pro; Vagrant-Manager: 1.0.0.6

**Comment by deveres** [comment]
Hi,
try to use 
https://github.com/deveres/vagrant-manager-windows/releases/tag/1.0.0.8

**Comment by chriswayoub** [comment]
PR #48 has been merged and this is working as of 1.0.2.2
