### ISSUE TITLE
Vagrant folder on different drive

### ISSUE THREAD

**Issue by grappler** [lanayotech/vagrant-manager-windows#8]
I had issues making it work because the vagrant folder is on a different drive and thus would the require `/d` to be used.

**Comment by cfoellmann** [comment]
can you please release this patched version?
This is blocking a lot of use cases.

**Comment by amitailanciano** [comment]
We'll this patched out as soon as possible, the only reason there hasn't been a new release is because issue #1 is as of yet unresolved, we'll take another stab at it and release a new version either way

**Comment by amitailanciano** [comment]
Release 1.0.0.3 should resolve this issue
