### ISSUE TITLE
Unsigned installer

### ISSUE THREAD

**Issue by cfoellmann** [lanayotech/vagrant-manager-windows#9]
For some people the unsigned installer can be _a little_ off putting, right?

I have not the faintest idea about C# and/or Windows programming so I am not sure if it is possible but StartSSL https://www.startssl.com/?app=39 issues (nearly) free certs.
Maybe that is a possibility.

**Comment by amitailanciano** [comment]
We're not currently planning on implementing this, perhaps in a future update
